name: Refresh Content

on:
  schedule:
    # Run every 4 hours: 6 AM, 10 AM, 2 PM, 6 PM, 10 PM UTC
    - cron: '0 6,10,14,18,22 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh Fantasy Red Zone Content
        run: |
          curl -X GET "${{ secrets.SITE_URL }}/api/cron/daily?secret=${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-Content-Refresh"
